// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnwgnaneejkknokwpkwa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRud2duYW5lZWpra25va3dwa3dhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNDQ0NTEsImV4cCI6MjA3MDkyMDQ1MX0.G9NSvp59zg0pNEPWA8c5qECnfvri9MYUEJyqpUk2ILQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});